'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9179
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Theremino_Spectrometer.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    Friend Shared ReadOnly Property bepbeep() As System.IO.UnmanagedMemoryStream
        Get
            Return ResourceManager.GetStream("bepbeep", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Click2a() As System.IO.UnmanagedMemoryStream
        Get
            Return ResourceManager.GetStream("Click2a", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Click2b() As System.IO.UnmanagedMemoryStream
        Get
            Return ResourceManager.GetStream("Click2b", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Click2c() As System.IO.UnmanagedMemoryStream
        Get
            Return ResourceManager.GetStream("Click2c", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Click3a() As System.IO.UnmanagedMemoryStream
        Get
            Return ResourceManager.GetStream("Click3a", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ComClose() As System.IO.UnmanagedMemoryStream
        Get
            Return ResourceManager.GetStream("ComClose", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ComClose2() As System.IO.UnmanagedMemoryStream
        Get
            Return ResourceManager.GetStream("ComClose2", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ComOpen() As System.IO.UnmanagedMemoryStream
        Get
            Return ResourceManager.GetStream("ComOpen", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property HonkHonk() As System.IO.UnmanagedMemoryStream
        Get
            Return ResourceManager.GetStream("HonkHonk", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Laser() As System.IO.UnmanagedMemoryStream
        Get
            Return ResourceManager.GetStream("Laser", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property Success2() As System.IO.UnmanagedMemoryStream
        Get
            Return ResourceManager.GetStream("Success2", resourceCulture)
        End Get
    End Property
End Class
